package com.example.plugins.model.impl;

import com.example.plugins.model.Parts;
import com.example.plugins.service.PartsLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Parts service. Represents a row in the &quot;nec_Parts&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PartsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PartsImpl
 * @see com.example.plugins.model.Parts
 * @generated
 */
public abstract class PartsBaseImpl extends PartsModelImpl implements Parts {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a parts model instance should use the {@link Parts} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PartsLocalServiceUtil.addParts(this);
        } else {
            PartsLocalServiceUtil.updateParts(this);
        }
    }
}
